name: Build images

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '20 2 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUSH_IMAGES: ${{ github.ref == 'refs/heads/main' }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Latest mc release
        id: mc
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: minio/mc
          excludes: prerelease, draft
      -
        name: Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
            suffix=-alpine,onlatest=false
          tags: |
            ${{ steps.mc.outputs.release }}
          images: pgils/mc
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        if: ${{ env.PUSH_IMAGES == 'true' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: "MC_RELEASE=${{ steps.mc.outputs.release }}"
          platforms: linux/amd64,linux/arm64
          push: ${{ env.PUSH_IMAGES }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
