name: Build images

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '20 2 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Latest mc release
        id: mc
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: minio/mc
          excludes: prerelease, draft
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: "MC_RELEASE=${{ steps.mc.outputs.release }}"
          platforms: linux/amd64,linux/arm64
          #push: ${{ github.ref == 'refs/heads/main' }}
          push: true
          repository: pgils/mc
          tags: latest, ${{ steps.mc.outputs.release }}-alpine
